services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  express-service:
    build: ./express-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - minio

  pdf-downloader-service:
    build: ./pdf-downloader-service
    depends_on:
      - rabbitmq
      - minio

volumes:
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local
