services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: adminadminadmin
      MINIO_ROOT_PASSWORD: adminadminadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  express-service:
    build: ./express-service
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - minio
      - mongodb
      - elasticsearch

  pdf-downloader-service:
    build: ./pdf-downloader-service
    dns:
      - 8.8.8.8
    depends_on:
      - rabbitmq
      - minio
      - mongodb
      - elasticsearch

volumes:
  minio_data:
    driver: local
  rabbitmq_data:
    driver: local
  mongo_data:
    driver: local
  es_data:
    driver: local
